version: "3.5"

services:
  cat-hats:
    build: ./cat-hats
    network_mode: "host"
    volumes:
      - ./cat-hats:/cat-hats

  api-gateway:
    build: ./api-gateway
    network_mode: "host"
    volumes:
      - ./api-gateway:/api-gateway

  user-service:
    build: ./user-service
    network_mode: "host"
    volumes:
      - ./user-service:/user-service

  catalog-service:
    build: ./catalog-service
    network_mode: "host"
    volumes:
      - ./catalog-service:/catalog-service

  scheduling-service:
    build: ./scheduling-service
    network_mode: "host"
    volumes:
      - ./scheduling-service:/scheduling-service
